### ISSUE TITLE
Comment needs update

### ISSUE THREAD

**Issue by alecthegeek** [PaperCutSoftware/PaperCutExamples#10]
The text

`# Script to add user account notes to account_configurations.csv` is incorrect. It should be a "shared accounts"

[addInfoToCSVreport.py](https://github.com/PaperCutSoftware/PaperCutExamples/blob/master/PublicWebServicesAPI_AND_servercommandScripts/addInfoToCSVreport.py)

**Comment by RyanReichenberg** [comment]
37740e4b965a59fc1508b897d791900017daae42
