### ISSUE TITLE
Unable to compile ServerProxyCommand

### ISSUE THREAD

**Issue by mcgurdan** [PaperCutSoftware/PaperCutExamples#11]
Please can you share a compiled version?

**Comment by mcgurdan** [comment]
and CookComputing.XmlRpcV2.dll please

**Comment by Joffcom** [comment]
I put the [cook computing dll](https://files.gitter.im/PaperCutSoftware/PaperCutExamples/HYkE/CookComputing.XmlRpcV2.dll) in the Gitter chat the other day along with a fixed version of the [ServerCommandProxy](https://files.gitter.im/PaperCutSoftware/PaperCutExamples/ZnLM/ServerCommandProxy.cs) code if it helps.

**Comment by Joffcom** [comment]
@alecthegeek Just checked my 19 install and the change for the ServerCommandProxy c# example has still not been updated.

**Comment by RyanReichenberg** [comment]
I'm going to go ahead and close this. Feel free to comment @mcgurdan  if you still have issues for this particular issue, or please open a new ticket if you any other problems.

Thanks!
