### ISSUE TITLE
Printer Properties page is blank

### ISSUE THREAD

**Issue by ksaylor11** [PaperCutSoftware/PaperCutExamples#14]
This [link](https://github.com/PaperCutSoftware/PaperCutExamples/wiki/Configuring-And-Applying-Changes-To-Devices) from the wiki is blank. I see the link for it [here](https://github.com/PaperCutSoftware/PaperCutExamples/wiki/Configuring-Printer-Changes). Is there an additional place this sort of documentation can be found?

**Comment by RyanReichenberg** [comment]
Hi Ksaylor,

Thanks for the heads up. I will go ahead and fix that.
