### ISSUE TITLE
api.getUserProperties not working

### ISSUE THREAD

**Issue by ngekoding** [PaperCutSoftware/PaperCutExamples#21]
I just try to get user properties as mentioned on https://www.papercut.com/support/resources/manuals/ng-mf/common/topics/tools-web-services.html#tools-web-services-examples

I was tried to use `getUserProperty` and working fine. 
But when I try to get multiple user properties using `getUserProperties` always get error, I don't know why?

Here my code:

```
$client = new PhpXmlRpc\Client('/rpc/api/xmlrpc', $host, $port);
$client->return_type = 'phpvals';
$request = new PhpXmlRpc\Request('api.getUserProperties', [ 
	new PhpXmlRpc\Value('<TOKEN>', 'string'),
	new PhpXmlRpc\Value('<USERNAME>', 'string'),
	new PhpXmlRpc\Value('email', 'string'),
	new PhpXmlRpc\Value('notes', 'string')
]);

$response = $client->send($request);
		
if (!$response->faultCode()) {
	return $response->value();
}

return json_encode([
	'error' => true,
	'code' => $response->faultCode(),
	'reason' => $response->faultString(),
]);
```

And here the error I get:

```
{
  "error": true,
  "code": -1,
  "reason": "java.lang.NoSuchMethodException: biz.papercut.pcng.webservices.xmlrpc.ApiRPCHandler$$EnhancerBySpringCGLIB$$57c74f91.getUserProperties(java.lang.String, java.lang.String, java.lang.String, java.lang.String)"
}
```

Hope anyone can help, thanks in advance.

**Comment by alecthegeek** [comment]
get user properties takes an array, not strings

```
public java.util.Vector<java.lang.String> getUserProperties​(java.lang.String userName, java.util.Vector<java.lang.String> propertyNames)
```

**Comment by ngekoding** [comment]
> get user properties takes an array, not strings
> 
> ```
> public java.util.Vector<java.lang.String> getUserProperties​(java.lang.String authToen, java.lang.String userName, java.util.Vector<java.lang.String> propertyNames)
> ```

Thank you, everything working well now.

Can you tell me where can I found the detail method implementation? 
Because I can't found it in this documentation https://www.papercut.com/support/resources/manuals/ng-mf/common/topics/tools-web-services.html#tools-web-services-examples, so I just code without know what exactly to do.

**Comment by Joffcom** [comment]
If you go to the Java examples folder there is a doc folder that will have everything you need in it.

**Comment by ngekoding** [comment]
> If you go to the Java examples folder there is a doc folder that will have everything you need in it.

Thank you

**Comment by alecthegeek** [comment]
More information here

https://www.papercut.com/kb/Main/TopTipsForUsingThePublicWebServicesAPI
