### ISSUE TITLE
gitter button broken

### ISSUE THREAD

**Issue by silentdevnull** [PaperCutSoftware/PaperCutExamples#25]
When you click on the gitter.im button in the readme file it gets 404.

**Comment by alecthegeek** [comment]
Thanks. The Gitter chat was closed and I forgot to remove the link.

Please join the Google group instead

**Comment by alecthegeek** [comment]
Fixed with https://github.com/PaperCutSoftware/PaperCutExamples/commit/392f284939bb498d621600c68a997a8d3559bc77

**Comment by silentdevnull** [comment]
Thank you @alecthegeek. I submitted the request for the google group.
